server:
  port: 8080
spring:
  datasource:
    url: jdbc:postgresql://192.168.3.178:5432/game_service
    username: leonardo.alonso
    password: aea4f8261e
  jpa:
    hibernate:
      ddl-auto: update
